name: release

on:
  workflow_dispatch:
    inputs:
      subproject:
        description: "Subproject to release"
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17.0.9'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Run tests
        run: ./gradlew clean build

      - name: Publish staging
        run: ./gradlew :${{ github.event.inputs.subproject }}:publish

      - name: Prepare keys
        env:
          PUBLIC_CONTENT: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_CONTENT: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PUBLIC_CONTENT" > public.key
          echo "$PRIVATE_CONTENT" > private.key
      
      - name: Create release
        run: ./gradlew jreleaserDeploy -PreleasedSubProject=${{ github.event.inputs.subproject }} || exit 0
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_PASSWORD }}
